"""empty message

Revision ID: 080e67ccf29a
Revises: 
Create Date: 2022-09-10 20:41:40.061494

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '080e67ccf29a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('qq', sa.String(length=20), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=False),
    sa.Column('cookie', sa.String(length=300), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cookie'),
    sa.UniqueConstraint('qq'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_user')
    # ### end Alembic commands ###
