"""empty message

Revision ID: dc8d45531895
Revises: 080e67ccf29a
Create Date: 2022-09-10 21:12:56.505543

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dc8d45531895'
down_revision = '080e67ccf29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoleData',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rolename', sa.String(length=10), nullable=False),
    sa.Column('rolepic_url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename'),
    sa.UniqueConstraint('rolepic_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoleData')
    # ### end Alembic commands ###
